stages:
  - build
  - test
  - collect

########################################################################
#
#                         linux - Build & Test
#
########################################################################

.build_linux: &build_linux
  tags:
    - docker
  stage: build
  script:
    - export PATH=$PATH:$HOME/miniconda3/condabin
    - bash -e scripts/build.sh --num-procs=4 --python=$PYTHON --dist
  artifacts:
    expire_in: 2 weeks
    paths:
      - build/dist/

build_wheel_linux_py27:
  <<: *build_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  variables:
    PYTHON: "2.7"

build_wheel_linux_py35:
  <<: *build_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  variables:
    PYTHON: "3.5"

build_wheel_linux_py36:
  <<: *build_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  variables:
    PYTHON: "3.6"

build_wheel_linux_py37:
  <<: *build_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  variables:
    PYTHON: "3.7"

.test_linux: &test_linux
  tags:
    - docker
  stage: test
  script:
    - bash -e scripts/test.sh --wheel-path=${WHEEL_PATH} --python=${PYTHON}

test_wheel_linux_py27:
  <<: *test_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  dependencies:
    - build_wheel_linux_py27
  variables:
    WHEEL_PATH: build/dist/coremltools*cp27-none-manylinux1_x86_64.whl
    PYTHON: "2.7"

test_wheel_linux_py35:
  <<: *test_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  dependencies:
    - build_wheel_linux_py35
  variables:
    WHEEL_PATH: build/dist/coremltools*cp35-none-manylinux1_x86_64.whl
    PYTHON: "3.5"

test_wheel_linux_py36:
  <<: *test_linux
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  dependencies:
    - build_wheel_linux_py36
  variables:
    WHEEL_PATH: build/dist/coremltools*cp36-none-manylinux1_x86_64.whl
    PYTHON: "3.6"

test_wheel_linux_py37:
  <<: *test_linux
  image: registry.gitlab.com/coremltools/coremltools/build-image-ubuntu:1.0.0
  dependencies:
    - build_wheel_linux_py37
  variables:
    WHEEL_PATH: build/dist/coremltools*cp37-none-manylinux1_x86_64.whl
    PYTHON: "3.7"


#########################################################################
##
##                         macOS - Build & Test
##
#########################################################################

.build_macos: &build_macos
    tags:
      - macos10.15
    stage: build
    script:
      - bash -e scripts/build.sh --num-procs=4 --python=$PYTHON --dist
    artifacts:
      expire_in: 2 weeks
      paths:
        - build/dist/

build_wheel_macos_py27:
  <<: *build_macos
  variables:
    PYTHON: "2.7"

## Uses Python 3.5 from python.org (already on build machine)
build_wheel_macos_py35:
  <<: *build_macos
  variables:
    PYTHON: "3.5"

## Uses Python 3.6 from python.org (already on build machine)
build_wheel_macos_py36:
  <<: *build_macos
  variables:
    PYTHON: "3.6"

## Uses Python 3.7 from python.org (already on build machine)
build_wheel_macos_py37:
  <<: *build_macos
  variables:
    PYTHON: "3.7"

.test_macos: &test_macos
  stage: test
  script:
    - bash -e scripts/test.sh --wheel-path=${WHEEL_PATH} --python=${PYTHON}

test_wheel_macos_13_py27:
  <<: *test_macos
  tags:
    - macos10.13
  dependencies:
    - build_wheel_macos_py27
  variables:
    WHEEL_PATH: build/dist/*cp27*10_13*
    PYTHON: "2.7"

test_wheel_macos_14_py27:
  <<: *test_macos
  tags:
    - macos10.14
  dependencies:
    - build_wheel_macos_py27
  variables:
    WHEEL_PATH: build/dist/*cp27*10_14*
    PYTHON: "2.7"

test_wheel_macos_15_py27:
  <<: *test_macos
  tags:
    - macos10.15
  dependencies:
    - build_wheel_macos_py27
  variables:
    WHEEL_PATH: build/dist/*cp27*10_15*
    PYTHON: "2.7"

test_wheel_macos_15_py35:
  <<: *test_macos
  tags:
    - macos10.15
  dependencies:
    - build_wheel_macos_py35
  variables:
    WHEEL_PATH: build/dist/*cp35*10_15*
    PYTHON: "3.5"

test_wheel_macos_15_py36:
  <<: *test_macos
  tags:
    - macos10.15
  dependencies:
    - build_wheel_macos_py36
  variables:
    WHEEL_PATH: build/dist/*cp36*10_15*
    PYTHON: "3.6"

test_wheel_macos_15_py37:
  <<: *test_macos
  tags:
    - macos10.15
  dependencies:
    - build_wheel_macos_py37
  variables:
    WHEEL_PATH: build/dist/*cp37*10_15*
    PYTHON: "3.7"

#########################################################################
##
##                        Make docs 
##
#########################################################################
build_documentation:
  tags:
    - docker
  stage: test
  image: registry.gitlab.com/zach_nation/coremltools/build-image-ubuntu-14.04:1.0.3
  script:
    - bash -e scripts/make_docs.sh --wheel-path=${WHEEL_PATH} --python=${PYTHON} 
  dependencies:
    - build_wheel_linux_py27
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - build/dist/
  variables:
    WHEEL_PATH: build/dist/coremltools*cp27-none-manylinux1_x86_64.whl
    PYTHON: /usr/local/bin/python

#########################################################################
##
##                       Collect arfifacts 
##
#########################################################################
collect_artifacts:
  tags:
    - docker
  services:
    - docker:18.09-dind
  image: alpine:latest
  stage: collect
  script:
    echo "Collect artifacts (wheels and documentation)"
  dependencies:
    - build_wheel_linux_py27
    - build_wheel_linux_py35
    - build_wheel_linux_py36
    - build_wheel_linux_py37
    - build_wheel_macos_py27
    - build_wheel_macos_py35
    - build_wheel_macos_py36
    - build_wheel_macos_py37
    - build_documentation
  artifacts:
    expire_in: 2 weeks
    paths:
      - build/dist/
